In [17]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [18]:
carros=pd.read_csv('carros.csv')
display(carros)

,Unnamed: 0,fabricante,modelo,ano,combustivel,hp,cilindros,tipo_transmissao,tracao,num_portas,categoria,tamanho,estilo,km_por_l_estrada,km_por_l_cidade,popularidade,preco_venda,label
0,0,BMW,1 Series M,2011,gasolina premium,335.0,6.0,MANUAL,tracao_traseira,2.0,"Audio de Fabrica,Luxo,Alta-Performance",compacto,Cupê,26,19,3916,46135,BMW 1 Series M
1,1,BMW,1 Series,2011,gasolina premium,300.0,6.0,MANUAL,tracao_traseira,2.0,"Luxo,Performance",compacto,Conversível,28,19,3916,40650,BMW 1 Series
2,2,BMW,1 Series,2011,gasolina premium,300.0,6.0,MANUAL,tracao_traseira,2.0,"Luxo,Alta-Performance",compacto,Cupê,28,20,3916,36350,BMW 1 Series
3,3,BMW,1 Series,2011,gasolina premium,230.0,6.0,MANUAL,tracao_traseira,2.0,"Luxo,Performance",compacto,Cupê,28,18,3916,29450,BMW 1 Series
4,4,BMW,1 Series,2011,gasolina premium,230.0,6.0,MANUAL,tracao_traseira,2.0,Luxo,compacto,Conversível,28,18,3916,34500,BMW 1 Series
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,11909,Acura,ZDX,2012,gasolina premium,300.0,6.0,AUTOMATICO,quatro_por_quatro AWD,4.0,"Crossover,Hatch,Luxo",regular,4dr Hatchback,23,16,204,46120,Acura ZDX
11910,11910,Acura,ZDX,2012,gasolina premium,300.0,6.0,AUTOMATICO,quatro_por_quatro AWD,4.0,"Crossover,Hatch,Luxo",regular,4dr Hatchback,23,16,204,56670,Acura ZDX
11911,11911,Acura,ZDX,2012,gasolina premium,300.0,6.0,AUTOMATICO,quatro_por_quatro AWD,4.0,"Crossover,Hatch,Luxo",regular,4dr Hatchback,23,16,204,50620,Acura ZDX
11912,11912,Acura,ZDX,2013,gasolina aditivada,300.0,6.0,AUTOMATICO,quatro_por_quatro AWD,4.0,"Crossover,Hatch,Luxo",regular,4dr Hatchback,23,16,204,50920,Acura ZDX
11913,11913,Lincoln,Zephyr,2006,gasolina comum,221.0,6.0,AUTOMATICO,tracao_dianteira,4.0,Luxo,regular,Sedan,26,17,61,28995,Lincoln Zephyr

In [19]:
carros.shape

(11914, 18)

In [20]:
carros.isnull().sum()

Unnamed: 0          0
fabricante          0
modelo              0
ano                 0
combustivel         0
hp                  0
cilindros           0
tipo_transmissao    0
tracao              0
num_portas          0
categoria           0
tamanho             0
estilo              0
km_por_l_estrada    0
km_por_l_cidade     0
popularidade        0
preco_venda         0
label               0
dtype: int64

In [21]:
#Caso houvessem dados faltantes:
carros['categoria'].fillna('INDEFINIDO',inplace=True)
carros['combustivel'].fillna('alcool',inplace=True)
carros['num_portas'].fillna(2,inplace=True)

In [22]:
#Convertendo as colunas para categorias
carros['combustivel']=carros['combustivel'].astype('category')
carros['tipo_transmissao']=carros['tipo_transmissao'].astype('category')
carros['tracao']=carros['tracao'].astype('category')
carros['categoria']=carros['categoria'].astype('category')
carros['tamanho']=carros['tamanho'].astype('category')
carros['estilo']=carros['estilo'].astype('category')
carros['label']=carros['label'].astype('category')

In [23]:
#Substituindo os valores categóricos por numéricos
cat_columns=carros.select_dtypes(['category']).columns
carros[cat_columns]=carros[cat_columns].apply(lambda x: x.cat.codes)
carros

,Unnamed: 0,fabricante,modelo,ano,combustivel,hp,cilindros,tipo_transmissao,tracao,num_portas,categoria,tamanho,estilo,km_por_l_estrada,km_por_l_cidade,popularidade,preco_venda,label
0,0,BMW,1 Series M,2011,7,335.0,6.0,3,3,2.0,3,0,5,26,19,3916,46135,66
1,1,BMW,1 Series,2011,7,300.0,6.0,3,3,2.0,68,0,4,28,19,3916,40650,65
2,2,BMW,1 Series,2011,7,300.0,6.0,3,3,2.0,65,0,5,28,20,3916,36350,65
3,3,BMW,1 Series,2011,7,230.0,6.0,3,3,2.0,68,0,5,28,18,3916,29450,65
4,4,BMW,1 Series,2011,7,230.0,6.0,3,3,2.0,64,0,4,28,18,3916,34500,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,11909,Acura,ZDX,2012,7,300.0,6.0,0,1,4.0,19,2,2,23,16,204,46120,17
11910,11910,Acura,ZDX,2012,7,300.0,6.0,0,1,4.0,19,2,2,23,16,204,56670,17
11911,11911,Acura,ZDX,2012,7,300.0,6.0,0,1,4.0,19,2,2,23,16,204,50620,17
11912,11912,Acura,ZDX,2013,5,300.0,6.0,0,1,4.0,19,2,2,23,16,204,50920,17
11913,11913,Lincoln,Zephyr,2006,6,221.0,6.0,0,2,4.0,64,2,12,26,17,61,28995,566

In [24]:
carros.loc[:, 'ano' :]=carros.to_csv('carros_categorical.csv', index= False)

Preparação, Seaparação dos Dados de Treinamento de uma Árvore de Decisão

In [25]:
df_clientes=pd.read_csv('dados_clientes_nome.csv')
display(df_clientes)

     nome  idade  nacionalidade  altura  peso  sexo  gosta de futebol  salario
0    Aldo     22              0    1.70    75     0                 1     2500
1    Beto     52              1    1.75    80     0                 1     2500
2     Bia     31              1    1.50    65     1                 1     4500
3  Carlos     65              1    1.95    86     0                 0     6500
4   Diego     17              0    1.81    95     0                 1     1500
5   Daina     54              0    1.65    80     1                 0     3500
6   Carol     30              0    1.90   105     1                 1     1200
7   Fabia     25              1    1.85    65     1                 1     2245
8   Felix     49              0    1.71    75     0                 0    25000
9    Gaia     26              1    1.81    80     1                 1     8000

In [26]:
from sklearn import tree

In [27]:
atributos=['idade','nacionalidade','altura','peso','sexo', 'salario']
X_treino=df_clientes.loc[:,atributos].to_numpy()
y_treino=df_clientes['gosta de futebol'].to_numpy()

In [28]:
clf=tree.DecisionTreeClassifier(criterion='gini',splitter='best',
                                max_depth=10, min_samples_split=5,
                                min_samples_leaf=1, max_features=6)
clf=clf.fit(X_treino,y_treino)

In [29]:
categorias_gosta_futebol=['Gosta de futebol','Não gosta futebol']

In [30]:
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_predict
cv_results = cross_val_predict(clf, X_treino, y_treino, cv=3)
print(classification_report(y_treino, cv_results, target_names=categorias_gosta_futebol))

                   precision    recall  f1-score   support

 Gosta de futebol       0.25      0.33      0.29         3
Não gosta futebol       0.67      0.57      0.62         7

         accuracy                           0.50        10
        macro avg       0.46      0.45      0.45        10
     weighted avg       0.54      0.50      0.52        10

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np

# Lê o dataset de carros
carros = pd.read_csv("carros_categorical.csv")

carros

,Unnamed: 0,fabricante,modelo,ano,combustivel,hp,cilindros,tipo_transmissao,tracao,num_portas,categoria,tamanho,estilo,km_por_l_estrada,km_por_l_cidade,popularidade,preco_venda,label
0,0,BMW,1 Series M,2011,7,335.0,6.0,3,3,2.0,3,0,5,26,19,3916,46135,66
1,1,BMW,1 Series,2011,7,300.0,6.0,3,3,2.0,68,0,4,28,19,3916,40650,65
2,2,BMW,1 Series,2011,7,300.0,6.0,3,3,2.0,65,0,5,28,20,3916,36350,65
3,3,BMW,1 Series,2011,7,230.0,6.0,3,3,2.0,68,0,5,28,18,3916,29450,65
4,4,BMW,1 Series,2011,7,230.0,6.0,3,3,2.0,64,0,4,28,18,3916,34500,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,11909,Acura,ZDX,2012,7,300.0,6.0,0,1,4.0,19,2,2,23,16,204,46120,17
11910,11910,Acura,ZDX,2012,7,300.0,6.0,0,1,4.0,19,2,2,23,16,204,56670,17
11911,11911,Acura,ZDX,2012,7,300.0,6.0,0,1,4.0,19,2,2,23,16,204,50620,17
11912,11912,Acura,ZDX,2013,5,300.0,6.0,0,1,4.0,19,2,2,23,16,204,50920,17
11913,11913,Lincoln,Zephyr,2006,6,221.0,6.0,0,2,4.0,64,2,12,26,17,61,28995,566

In [32]:
# Seleciona apenas as colunas necessárias
X = carros.loc[:, 'ano':'preco_venda'].to_numpy()
y = carros['label'].to_numpy()

In [33]:
# Divide o conjunto em treinamento e teste, na proporção 80-20
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.25,                                                         
                                                        random_state=123, 
                                                        shuffle=True)

caracteristicas = list(carros.columns[2:-1])

carros['fabricante'] = carros ['fabricante'].astype('category')

categorias = carros['fabricante'].cat.categories

print("Tamanho do conjunto de treinamento: {}".format(len(X_treino)))
print("Tamanho do conjunto de testes: {}".format(len(X_teste)))
print("Quantidade de características: {}".format(len(caracteristicas)))
print("Quantidade de classes ou categorias: {}".format(len(carros ['fabricante'].cat.categories)))

Tamanho do conjunto de treinamento: 8935
Tamanho do conjunto de testes: 2979
Quantidade de características: 15
Quantidade de classes ou categorias: 48

In [34]:
# Conta a quantidade de categorias de serviço
categ_count = carros['fabricante'].value_counts()
print(str(categ_count))

fabricante
Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
McLaren             5
Alfa Romeo          5
Spyker              3
Bugatti             3
Genesis             3
Name: count, dtype: int64

In [35]:
# Treina um algoritmo de árvore de decisão com os dados
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion = "gini", splitter = "best", 
                                  max_depth = 3,  min_samples_split = 5,
                                  min_samples_leaf = 2, max_features = 2)
clf_gini_best = clf.fit(X_treino, y_treino)

In [36]:
# Avalia o desempenho do modelo treinado
import numpy as np
from sklearn.metrics import classification_report

y_pred = clf_gini_best.predict(X_teste)